SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `testbot`
--

--
-- Dumping data for table `altertables`
--

INSERT INTO `altertables` (`id`, `statement`) VALUES
(210, 'CREATE TABLE `badWords` (`badWord` varchar(15) NOT NULL,`cost` int(11) NOT NULL DEFAULT \'10\',`counter` int(11) NOT NULL DEFAULT \'0\') ENGINE=InnoDB DEFAULT CHARSET=latin1'),
(211, 'CREATE TABLE `list` (`thing` varchar(255) NOT NULL) ENGINE=MEMORY DEFAULT CHARSET=latin1 COMMENT=\'For sorting a list\''),
(212, 'CREATE TABLE `prefabCopies` (`owner` bigint(17) NOT NULL DEFAULT \'0\',`name` varchar(50) NOT NULL DEFAULT \'\',`x1` int(11) NOT NULL DEFAULT \'0\',`x2` int(11) NOT NULL DEFAULT \'0\',`y1` int(11) NOT NULL DEFAULT \'0\',`y2` int(11) NOT NULL DEFAULT \'0\',`z1` int(11) NOT NULL DEFAULT \'0\',`z2` int(11) NOT NULL DEFAULT \'0\',`blockName` VARCHAR(50) NOT NULL DEFAULT \'\',`rotation` INT NOT NULL DEFAULT \'0\', PRIMARY KEY (`owner`,`name`)) ENGINE=InnoDB DEFAULT CHARSET=latin1'),
(213, 'CREATE TABLE `memEntities` (`entityID` bigint(20) NOT NULL,`type` varchar(20) NOT NULL DEFAULT \'\',`name` varchar(30) NOT NULL DEFAULT \'\',`x` int(11) NOT NULL DEFAULT \'0\',`y` int(11) NOT NULL DEFAULT \'0\',`z` int(11) DEFAULT \'0\',`dead` tinyint(1) NOT NULL DEFAULT \'0\',`health` int(11) NOT NULL DEFAULT \'0\', PRIMARY KEY (`entityID`)) ENGINE=InnoDB DEFAULT CHARSET=latin1'),
(214, 'CREATE TABLE `waypoints` (`steam` varchar(17) NOT NULL,`name` varchar(20) NOT NULL,`x` int(11) NOT NULL DEFAULT \'0\',`y` int(11) NOT NULL DEFAULT \'0\',`z` int(11) NOT NULL DEFAULT \'0\',`shared` int(11) NOT NULL DEFAULT \'0\', PRIMARY KEY (`steam`,`name`)) ENGINE=InnoDB DEFAULT CHARSET=latin1'),
(215, 'CREATE TABLE `gimmeZombies` (`zombie` varchar(50) NOT NULL,`minPlayerLevel` int(11) NOT NULL DEFAULT \'1\',`minArenaLevel` int(11) NOT NULL DEFAULT \'1\', PRIMARY KEY (`zombie`)) ENGINE=InnoDB DEFAULT CHARSET=latin1'),
(216, 'CREATE TABLE `miscQueue` (`id` bigint(20) NOT NULL AUTO_INCREMENT,`steam` bigint(17) NOT NULL,`command` varchar(100) NOT NULL,`action` varchar(15) NOT NULL,`value` int(11) NOT NULL DEFAULT \'0\', PRIMARY KEY (`id`)) ENGINE=MEMORY DEFAULT CHARSET=utf8'),
(217, 'CREATE TABLE `customCommands` (`commandID` int(11) NOT NULL AUTO_INCREMENT, `command` varchar(50) NOT NULL, `accessLevel` int(11) NOT NULL DEFAULT \'2\', `help` varchar(255) NOT NULL, PRIMARY KEY (`commandID`)) ENGINE=InnoDB DEFAULT CHARSET=latin1'),
(218, 'CREATE TABLE `whitelist` (`steam` varchar(17) NOT NULL, PRIMARY KEY (`steam`)) ENGINE=InnoDB DEFAULT CHARSET=latin1'),
(219, 'CREATE TABLE `otherEntities` (`entity` varchar(50) NOT NULL,`entityID` int(11) NOT NULL DEFAULT \'0\',`doNotSpawn` tinyint(4) NOT NULL DEFAULT \'0\', PRIMARY KEY (`entity`)) ENGINE=InnoDB DEFAULT CHARSET=latin1'),
(220, 'CREATE TABLE IF NOT EXISTS `helpCommands` (`commandID` int(11) NOT NULL AUTO_INCREMENT,`command` varchar(255) NOT NULL,`description` varchar(255) NOT NULL,`notes` text NOT NULL,`keywords` varchar(150) NOT NULL,`lastUpdate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,`accessLevel` int(11) NOT NULL DEFAULT \'99\',`ingameOnly` tinyint(1) NOT NULL DEFAULT \'0\', PRIMARY KEY (`commandID`)) ENGINE=InnoDB DEFAULT CHARSET=latin1'),
(221, 'CREATE TABLE IF NOT EXISTS `helpTopicCommands` (`topicID` int(11) NOT NULL,`commandID` int(11) NOT NULL, PRIMARY KEY (`topicID`, `commandID`)) ENGINE=InnoDB DEFAULT CHARSET=latin1'),
(222, 'CREATE TABLE IF NOT EXISTS `helpTopics` (`topicID` int(11) NOT NULL AUTO_INCREMENT,`topic` varchar(20) NOT NULL,`description` varchar(200) NOT NULL, PRIMARY KEY (`topicID`)) ENGINE=InnoDB DEFAULT CHARSET=latin1'),
(223, 'CREATE TABLE `staff` (`steam` bigint(17) NOT NULL DEFAULT \'0\',`adminLevel` int(11) NOT NULL DEFAULT \'2\',`blockDelete` tinyint(1) NOT NULL DEFAULT \'0\', PRIMARY KEY (`steam`)) ENGINE=InnoDB DEFAULT CHARSET=latin1'),
(224, 'CREATE TABLE IF NOT EXISTS `spawnableItems` (`itemName` varchar(100) NOT NULL, `deleteItem` tinyint(1) NOT NULL DEFAULT \'0\', `accessLevelRestriction` int(11) NOT NULL DEFAULT \'99\', `category` varchar(20) NOT NULL DEFAULT \'None\', `price` int(11) NOT NULL DEFAULT \'10000\', `stock` int(11) NOT NULL DEFAULT \'5000\', `idx` int(11) NOT NULL DEFAULT \'0\', `maxStock` int(11) NOT NULL DEFAULT \'5000\', `inventoryResponse` varchar(10) NOT NULL DEFAULT \'none\', `StackLimit` int(11) NOT NULL DEFAULT \'1000\', `newPlayerMaxInventory` int(11) NOT NULL DEFAULT \'-1\', `units` int(11) NOT NULL DEFAULT \'1\', PRIMARY KEY (`itemName`)) ENGINE=InnoDB DEFAULT CHARSET=latin1'),
(225, 'CREATE TABLE IF NOT EXISTS `reservedSlots` (`steam` varchar(17) NOT NULL,`timeAdded` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,`reserved` tinyint(1) NOT NULL DEFAULT \'0\',`staff` tinyint(1) NOT NULL DEFAULT \'0\',`totalPlayTime` int(11) NOT NULL DEFAULT \'0\',`deleteRow` TINYINT(1) NOT NULL DEFAULT \'0\',PRIMARY KEY (`steam`)) ENGINE=InnoDB DEFAULT CHARSET=latin1'),
(226, 'CREATE TABLE IF NOT EXISTS `botCommands` (`cmdCode` varchar(5) NOT NULL,`cmdIndex` int(11) NOT NULL,`accessLevel` int(11) NOT NULL DEFAULT \'0\',`enabled` tinyint(1) NOT NULL DEFAULT \'1\',`keywords` varchar(150) NOT NULL DEFAULT \'\',`shortDescription` varchar(255) NOT NULL DEFAULT \'\',`longDescription` varchar(1000) NOT NULL DEFAULT \'\',`sortOrder` int(11) NOT NULL DEFAULT \'0\',PRIMARY KEY (`cmdCode`,`cmdIndex`)) ENGINE=InnoDB DEFAULT CHARSET=latin1'),
(227, 'CREATE TABLE IF NOT EXISTS `timedEvents` (`timer` varchar(20) NOT NULL DEFAULT \'\',`delayMinutes` int(11) NOT NULL DEFAULT \'10\',`nextTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,`disabled` tinyint(1) NOT NULL DEFAULT \'0\',PRIMARY KEY (`timer`)) ENGINE=InnoDB DEFAULT CHARSET=latin1'),
(228, 'CREATE TABLE IF NOT EXISTS `botChat` (`botChatID` int(11) NOT NULL AUTO_INCREMENT,`triggerWords` varchar(255) NOT NULL DEFAULT \'\',`triggerPhrase` varchar(255) NOT NULL DEFAULT \'\',`accessLevelRestriction` int(11) NOT NULL DEFAULT \'99\',`mustAddressBot` tinyint(1) NOT NULL DEFAULT \'0\',PRIMARY KEY (`botChatID`)) ENGINE=InnoDB DEFAULT CHARSET=latin1'),
(229, 'CREATE TABLE IF NOT EXISTS `botChatResponses` (`botChatResponseID` int(11) NOT NULL AUTO_INCREMENT,`botChatID` int(11) NOT NULL DEFAULT \'0\',`response` varchar(300) NOT NULL DEFAULT \'\',PRIMARY KEY (`botChatResponseID`)) ENGINE=InnoDB DEFAULT CHARSET=latin1'),
(230, 'CREATE TABLE IF NOT EXISTS `webInterfaceQueue` (`id` int(11) NOT NULL AUTO_INCREMENT,`action` varchar(10) NOT NULL DEFAULT \'\',`actionTable` varchar(50) NOT NULL DEFAULT \'\',`actionQuery` text NOT NULL,PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=latin1'),
(231, 'CREATE TABLE IF NOT EXISTS `locationCategories` (`categoryName` varchar(20) NOT NULL,`minAccessLevel` int(11) NOT NULL DEFAULT \'99\',`maxAccessLevel` int(11) NOT NULL DEFAULT \'0\',PRIMARY KEY (`categoryName`)) ENGINE=InnoDB DEFAULT CHARSET=latin1'),
(232, 'ALTER TABLE `players` ADD COLUMN `waypoint2X` INT NOT NULL DEFAULT \'0\' , ADD COLUMN `waypoint2Y` INT NOT NULL DEFAULT \'0\' , ADD COLUMN `waypoint2Z` INT NOT NULL DEFAULT \'0\', ADD COLUMN `waypointsLinked` TINYINT(1) NOT NULL DEFAULT \'0\''),
(233, 'ALTER TABLE `players` ADD COLUMN `ircMute` TINYINT(1) NOT NULL DEFAULT \'0\''),
(234, 'ALTER TABLE `players` ADD COLUMN `chatColour` VARCHAR(8) NOT NULL DEFAULT \'\''),
(235, 'ALTER TABLE `players` ADD COLUMN `teleCooldown` INT NOT NULL DEFAULT \'0\''),
(236, 'ALTER TABLE `players` ADD COLUMN `reserveSlot` TINYINT NOT NULL DEFAULT \'0\''),
(237, 'ALTER TABLE `players` ADD COLUMN `prisonReleaseTime` INT NOT NULL DEFAULT \'0\''),
(238, 'ALTER TABLE `players` ADD COLUMN `maxWaypoints` INT NOT NULL DEFAULT \'2\''),
(239, 'ALTER TABLE `players` ADD COLUMN ircLogin varchar(20) NOT NULL DEFAULT \'\''),
(240, 'ALTER TABLE `players` ADD COLUMN `waypointCooldown` INT NOT NULL DEFAULT \'0\''),
(241, 'ALTER TABLE `players` CHANGE `location` `location` VARCHAR(15) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT \'\', CHANGE `maxWaypoints` `maxWaypoints` INT(11) NOT NULL DEFAULT \'2\''),
(242, 'ALTER TABLE `players` ADD `bail` INT NOT NULL DEFAULT \'0\''),
(243, 'ALTER TABLE `players` ADD `watchPlayerTimer` INT(11) NOT NULL DEFAULT \'0\''),
(244, 'ALTER TABLE `players` ADD `hackerScore` INT NOT NULL DEFAULT \'0\''),
(245, 'ALTER TABLE `players` ADD `pvpTeleportCooldown` INT NOT NULL DEFAULT \'0\''),
(246, 'ALTER TABLE `players` ADD `block` TINYINT(1) NOT NULL DEFAULT \'0\''),
(247, 'ALTER TABLE `players` ADD `removedClaims` INT NOT NULL DEFAULT \'0\''),
(248, 'ALTER TABLE `players` ADD `returnCooldown` INT NOT NULL DEFAULT \'0\''),
(249, 'ALTER TABLE `players` CHANGE `cash` `cash` FLOAT(11) NOT NULL DEFAULT \'0\''),
(250, 'ALTER TABLE `players` CHANGE `chatColour` `chatColour` VARCHAR(8) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT \'FFFFFF\''),
(251, 'ALTER TABLE `players` ADD `commandCooldown` INT NOT NULL DEFAULT \'0\''),
(252, 'ALTER TABLE `players` CHANGE `chatColour` `chatColour` VARCHAR(6) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT \'FFFFFF\''),
(253, 'ALTER TABLE `players` ADD `gimmeCooldown` INT NOT NULL DEFAULT \'0\''),
(254, 'ALTER TABLE `players` CHANGE `donorExpiry` `donorExpiry` INT(11) NOT NULL DEFAULT \'0\''),
(255, 'ALTER TABLE `players` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci'),
(256, 'ALTER TABLE `players` CHANGE `name` `name` VARCHAR(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL'),
(257, 'ALTER TABLE `players` CHANGE `aliases` `aliases` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL'),
(258, 'ALTER TABLE `server` ADD COLUMN `teleportCost` INT NOT NULL DEFAULT \'200\''),
(259, 'ALTER TABLE `server` ADD COLUMN `ircPrivate` TINYINT(1) NOT NULL DEFAULT \'0\''),
(260, 'ALTER TABLE `server` ADD COLUMN `waypointsPublic` TINYINT(1) NOT NULL DEFAULT \'0\''),
(261, 'ALTER TABLE `server` ADD COLUMN `waypointCost` INT NOT NULL DEFAULT \'0\''),
(262, 'ALTER TABLE `server` ADD COLUMN `waypointCooldown` INT NOT NULL DEFAULT \'0\''),
(263, 'ALTER TABLE `server` ADD COLUMN `waypointCreateCost` INT NOT NULL DEFAULT \'0\''),
(264, 'ALTER TABLE `server` ADD COLUMN `alertColour` VARCHAR(6) NOT NULL DEFAULT \'DC143C\''),
(265, 'ALTER TABLE `server` ADD COLUMN `warnColour` VARCHAR(6) NOT NULL DEFAULT \'FFA500\''),
(266, 'ALTER TABLE `server` ADD COLUMN `swearFine` INT NOT NULL DEFAULT \'5\''),
(267, 'ALTER TABLE `server` ADD COLUMN `commandPrefix` VARCHAR(1) NOT NULL DEFAULT \'/\''),
(268, 'ALTER TABLE `server` ADD COLUMN `chatlogPath` VARCHAR(200) NOT NULL DEFAULT \'\''),
(269, 'ALTER TABLE `server` ADD COLUMN `botVersion` VARCHAR(11) NOT NULL DEFAULT \'\''),
(270, 'ALTER TABLE `server` ADD COLUMN `packCost` INT NOT NULL DEFAULT \'0\''),
(271, 'ALTER TABLE `server` ADD COLUMN `baseCost` INT NOT NULL DEFAULT \'0\''),
(272, 'ALTER TABLE `server` ADD COLUMN `rebootHour` INT NOT NULL DEFAULT \'-1\''),
(273, 'ALTER TABLE `server` ADD COLUMN `rebootMinute` INT NOT NULL DEFAULT \'0\''),
(274, 'ALTER TABLE `server` ADD COLUMN `maxPrisonTime` INT NOT NULL DEFAULT \'-1\''),
(275, 'ALTER TABLE `server` ADD COLUMN `bailCost` INT NOT NULL DEFAULT \'0\''),
(276, 'ALTER TABLE `server` ADD COLUMN `maxWaypoints` INT NOT NULL DEFAULT \'2\''),
(277, 'ALTER TABLE `server` ADD COLUMN `teleportPublicCost` INT NOT NULL DEFAULT \'0\''),
(278, 'ALTER TABLE `server` ADD COLUMN `teleportPublicCooldown` INT NOT NULL DEFAULT \'0\''),
(279, 'ALTER TABLE `server` ADD COLUMN `reservedSlots` INT NOT NULL DEFAULT \'0\''),
(280, 'ALTER TABLE `server` ADD COLUMN `allowReturns` TINYINT(1) NOT NULL DEFAULT \'1\''),
(281, 'ALTER TABLE `server` ADD COLUMN `scanNoclip` TINYINT(1) NOT NULL DEFAULT \'1\''),
(282, 'ALTER TABLE `server` ADD COLUMN `scanEntities` TINYINT(1) NOT NULL DEFAULT \'0\''),
(283, 'ALTER TABLE `server` ADD COLUMN `CBSMFriendly` TINYINT(1) NOT NULL DEFAULT \'1\''),
(284, 'ALTER TABLE `server` ADD COLUMN `scanErrors` TINYINT(1) NOT NULL DEFAULT \'0\''),
(285, 'ALTER TABLE `server` ADD COLUMN disableTPinPVP TINYINT(1) NOT NULL DEFAULT \'0\''),
(286, 'ALTER TABLE `server` ADD COLUMN `ServerToolsDetected` TINYINT(1) NOT NULL DEFAULT \'0\''),
(287, 'ALTER TABLE `server` CHANGE `moneyName` `moneyName` VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT \'Zenny|Zennies\''),
(288, 'ALTER TABLE `server` CHANGE `rules` `rules` VARCHAR(1000) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT \'A zombie ate the server rules! Tell an admin.\''),
(289, 'ALTER TABLE `server` ADD `updateBot` INT(1) NOT NULL DEFAULT \'0\' COMMENT \'0 do not update, 1 stable branch, 2 testing branch\''),
(290, 'ALTER TABLE `server` ADD `alertSpending` TINYINT(1) NOT NULL DEFAULT \'0\''),
(291, 'ALTER TABLE `server` ADD `GBLBanThreshold` INT NOT NULL DEFAULT \'0\''),
(292, 'ALTER TABLE `server` CHANGE `shopCountdown` `shopCountdown` INT NOT NULL DEFAULT \'0\''),
(293, 'ALTER TABLE `server` ADD `lastBotsMessageID` INT NOT NULL DEFAULT \'0\' , ADD `lastBotsMessageTimestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP'),
(294, 'ALTER TABLE `server` ADD `gimmeZombies` TINYINT(1) NOT NULL DEFAULT \'1\''),
(295, 'ALTER TABLE `server` ADD `allowProxies` TINYINT(1) NOT NULL DEFAULT \'0\''),
(296, 'ALTER TABLE `server` ADD `SDXDetected` TINYINT(1) NOT NULL DEFAULT \'0\''),
(297, 'ALTER TABLE `server` ADD `enableWindowMessages` TINYINT(1) NOT NULL DEFAULT \'0\''),
(298, 'ALTER TABLE `server` ADD `updateBranch` VARCHAR(7) NOT NULL DEFAULT \'stable\''),
(299, 'ALTER TABLE `server` ADD `chatColourNewPlayer` VARCHAR(6) NOT NULL DEFAULT \'FFFFFF\' , ADD `chatColourPlayer` VARCHAR(6) NOT NULL DEFAULT \'FFFFFF\' , ADD `chatColourDonor` VARCHAR(6) NOT NULL DEFAULT \'FFFFFF\' , ADD `chatColourPrisoner` VARCHAR(6) NOT NULL DEFAULT \'FFFFFF\' , ADD `chatColourMod` VARCHAR(6) NOT NULL DEFAULT \'FFFFFF\' , ADD `chatColourAdmin` VARCHAR(6) NOT NULL DEFAULT \'FFFFFF\' , ADD `chatColourOwner` VARCHAR(6) NOT NULL DEFAULT \'FFFFFF\''),
(300, 'ALTER TABLE `server` ADD `commandCooldown` INT NOT NULL DEFAULT \'0\''),
(301, 'ALTER TABLE `server` CHANGE `ircAlerts` `ircAlerts` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT \'#new_alerts\''),
(302, 'ALTER TABLE `server` CHANGE `ircWatch` `ircWatch` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT \'#new_watch\''),
(303, 'ALTER TABLE `server` CHANGE `botName` `botName` VARCHAR(30) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT \'Bot\''),
(304, 'ALTER TABLE `server` CHANGE `ircMain` `ircMain` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT \'#new\''),
(305, 'ALTER TABLE `server` CHANGE `ircBotName` `ircBotName` VARCHAR(30) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT \'Bot\''),
(306, 'ALTER TABLE `server` CHANGE `shopLocation` `shopLocation` VARCHAR(30) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL'),
(307, 'ALTER TABLE `server` CHANGE `blacklistCountries` `blacklistCountries` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT \'CN\''),
(308, 'ALTER TABLE `server` CHANGE `moneyName` `moneyName` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT \'Zenny|Zennies\''),
(309, 'ALTER TABLE `server` CHANGE `ircTracker` `ircTracker` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT \'#new_tracker\''),
(310, 'ALTER TABLE `server` CHANGE `mapSize` `mapSize` INT(11) NOT NULL DEFAULT \'10000\''),
(311, 'ALTER TABLE `server` ADD `telnetPass` VARCHAR(50) NOT NULL'),
(312, 'ALTER TABLE `server` ADD `telnetPort` INT NOT NULL DEFAULT \'0\''),
(313, 'ALTER TABLE `server` ADD `feralRebootDelay` INT NOT NULL DEFAULT \'68\''),
(314, 'ALTER TABLE `server` ADD `pvpTeleportCooldown` INT NOT NULL DEFAULT \'0\''),
(315, 'ALTER TABLE `server` ADD `allowPlayerToPlayerTeleporting` TINYINT(1) NOT NULL DEFAULT \'1\''),
(316, 'ALTER TABLE `server` ADD `ircPort` INT NOT NULL DEFAULT \'6667\''),
(317, 'ALTER TABLE `server` CHANGE `botVersion` `botVersion` VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT \'\''),
(318, 'ALTER TABLE `server` CHANGE `updateBot` `updateBot` TINYINT(1) NOT NULL DEFAULT \'0\''),
(319, 'ALTER TABLE `server` ADD `botRestartHour` INT NOT NULL DEFAULT \'25\''),
(320, 'ALTER TABLE `server` ADD `trackingKeepDays` INT NOT NULL DEFAULT \'28\' , ADD `databaseMaintenanceFinished` TINYINT(1) NOT NULL DEFAULT \'1\''),
(321, 'ALTER TABLE `server` ADD `allowHomeTeleport` TINYINT(1) NOT NULL DEFAULT \'1\' , ADD `playerTeleportDelay` INT NOT NULL DEFAULT \'0\''),
(322, 'ALTER TABLE `server` ADD `allowPackTeleport` TINYINT(1) NOT NULL DEFAULT \'1\''),
(323, 'ALTER TABLE `server` ADD `gameVersion` VARCHAR(30) NOT NULL DEFAULT \'\''),
(324, 'ALTER TABLE `server` ADD `pvpIgnoreFriendlyKills` TINYINT(1) NOT NULL DEFAULT \'0\', ADD `allowStuckTeleport` TINYINT(1) NOT NULL DEFAULT \'1\''),
(325, 'ALTER TABLE `server` ADD `restrictIRC` TINYINT(1) NOT NULL DEFAULT \'0\''),
(326, 'ALTER TABLE `server` ADD `nextAnnouncement` INT NOT NULL DEFAULT \'1\''),
(327, 'ALTER TABLE `server` ADD `pvpAllowProtect` INT NOT NULL DEFAULT \'0\''),
(328, 'ALTER TABLE `server` ADD `hackerTPDetection` TINYINT(1) NOT NULL DEFAULT \'1\''),
(329, 'ALTER TABLE `server` CHANGE `updateBranch` `updateBranch` VARCHAR(30) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT \'stable\''),
(330, 'ALTER TABLE `server` CHANGE `moneyName` `moneyName` VARCHAR(40) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT \'Zenny|Zennies\''),
(331, 'ALTER TABLE `server` ADD `whitelistCountries` VARCHAR(50) NOT NULL DEFAULT \'\' , ADD `perMinutePayRate` INT NOT NULL DEFAULT \'0\' , ADD `disableWatchAlerts` TINYINT NOT NULL DEFAULT \'0\' , ADD `masterPassword` VARCHAR(50) NOT NULL DEFAULT \'\', ADD `allowBotRestarts` TINYINT NOT NULL DEFAULT \'0\', ADD `botOwner` VARCHAR(17) NOT NULL DEFAULT \'0\''),
(332, 'ALTER TABLE `server` CHANGE `pvpAllowProtect` `pvpAllowProtect` TINYINT NOT NULL DEFAULT \'0\''),
(333, 'ALTER TABLE `server` ADD `returnCooldown` INT NOT NULL DEFAULT \'0\''),
(334, 'ALTER TABLE `server` CHANGE `blockCountries` `blacklistCountries` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT \'CN,HK\''),
(335, 'ALTER TABLE `server` ADD `botRestartDay` INT NOT NULL DEFAULT \'7\''),
(336, 'ALTER TABLE `server` CHANGE `perMinutePayRate` `perMinutePayRate` FLOAT(11) NOT NULL DEFAULT \'0\''),
(337, 'ALTER TABLE `server` ADD `enableTimedClaimScan` TINYINT(1) NOT NULL DEFAULT \'1\', ADD `enableScreamerAlert` TINYINT(1) NOT NULL DEFAULT \'1\' , ADD `enableAirdropAlert` TINYINT(1) NOT NULL DEFAULT \'1\''),
(338, 'ALTER TABLE `server` ADD `spleefGameCoords` VARCHAR(20) NOT NULL DEFAULT \'4000 225 4000\''),
(339, 'ALTER TABLE `server` CHANGE `blacklistResponse` `blacklistResponse` VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT \'ban\''),
(340, 'ALTER TABLE `server` ADD `gimmeResetTime` INT NOT NULL DEFAULT \'120\', ADD `gimmeRaincheck` INT NOT NULL DEFAULT \'0\''),
(341, 'ALTER TABLE `server` ADD `pingKickTarget` VARCHAR(3) NOT NULL DEFAULT \'new\' , ADD `enableBounty` TINYINT(1) NOT NULL DEFAULT \'1\', ADD `mapSizeNewPlayers` INT NOT NULL DEFAULT \'10000\' , ADD `mapSizePlayers` INT NOT NULL DEFAULT \'10000\', ADD `shopResetDays` INT NOT NULL DEFAULT \'3\''),
(342, 'ALTER TABLE `server` ADD `telnetLogKeepDays` INT NOT NULL DEFAULT \'14\''),
(343, 'ALTER TABLE `server` CHANGE `IP` `IP` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT \'0.0.0.0\''),
(344, 'ALTER TABLE `server` ADD `dailyRebootHour` int(11) NOT NULL DEFAULT \'0\''),
(345, 'ALTER TABLE `server` ADD `maxWaypointsDonors` INT NOT NULL DEFAULT \'2\''),
(346, 'ALTER TABLE `server` CHANGE `lastBotsMessageTimestamp` `lastBotsMessageTimestamp` INT(11) NOT NULL DEFAULT \'0\''),
(347, 'ALTER TABLE `friends` ADD `autoAdded` TINYINT(1) NOT NULL DEFAULT \'0\''),
(348, 'ALTER TABLE `hotspots` ADD `action` VARCHAR(10) NOT NULL DEFAULT \'\''),
(349, 'ALTER TABLE `hotspots` ADD `destination` VARCHAR(20) NOT NULL DEFAULT \'\''),
(350, 'ALTER TABLE `inventoryChanges` ADD `flag` VARCHAR(3) DEFAULT \'\''),
(351, 'ALTER TABLE `donors` CHANGE `donorExpiry` `donorExpiry` INT(11) NULL DEFAULT NULL'),
(352, 'ALTER TABLE `gimmePrizes` ADD `quality` INT NOT NULL DEFAULT \'0\''),
(353, 'ALTER TABLE `gimmeZombies` ADD `entityID` INT NOT NULL DEFAULT \'0\''),
(354, 'ALTER TABLE `gimmeZombies` ADD `bossZombie` TINYINT(1) NOT NULL DEFAULT \'0\''),
(355, 'ALTER TABLE `gimmeZombies` ADD `doNotSpawn` TINYINT NOT NULL DEFAULT \'0\''),
(356, 'ALTER TABLE `gimmeZombies` ADD `maxHealth` INT NOT NULL DEFAULT \'0\''),
(357, 'ALTER TABLE `memShop` CHANGE `item` `item` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL'),
(358, 'ALTER TABLE `locations` ADD `timeOpen` INT NOT NULL DEFAULT \'0\' , ADD `timeClosed` INT NOT NULL DEFAULT \'0\''),
(359, 'ALTER TABLE `locations` ADD `allowWaypoints` TINYINT(1) NOT NULL DEFAULT \'1\' , ADD `allowReturns` TINYINT(1) NOT NULL DEFAULT \'1\', ADD `allowLeave` TINYINT(1) NOT NULL DEFAULT \'1\''),
(360, 'ALTER TABLE `miscQueue` CHANGE `command` `command` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL'),
(361, 'ALTER TABLE `miscQueue` CHANGE `id` `id` BIGINT( 20 ) NOT NULL AUTO_INCREMENT'),
(362, 'ALTER TABLE `locations` ADD `newPlayersOnly` TINYINT(1) NOT NULL DEFAULT \'0\''),
(363, 'ALTER TABLE `locations` ADD `minimumLevel` INT NOT NULL DEFAULT \'0\', ADD `maximumLevel` INT NOT NULL DEFAULT \'0\', ADD `dayClosed` INT NOT NULL DEFAULT \'0\''),
(364, 'ALTER TABLE `locations` ADD `dailyTaxRate` INT NOT NULL DEFAULT \'0\', ADD `bank` INT NOT NULL DEFAULT \'0\', ADD `prisonX` INT NOT NULL DEFAULT \'0\' , ADD `prisonY` INT NOT NULL DEFAULT \'0\' , ADD `prisonZ` INT NOT NULL DEFAULT \'0\''),
(365, 'ALTER TABLE `alerts` ADD `status` VARCHAR(30) NOT NULL DEFAULT \'\''),
(366, 'ALTER TABLE `IPBlacklist` ADD `DateAdded` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , ADD `botID` INT NOT NULL DEFAULT \'0\' , ADD `steam` BIGINT(17) NOT NULL DEFAULT \'0\' , ADD `playerName` VARCHAR(25) NOT NULL DEFAULT \'\''),
(367, 'ALTER TABLE `miscQueue` ADD `timerDelay` TIMESTAMP NOT NULL DEFAULT \'0000-00-00 00:00:00\''),
(368, 'ALTER TABLE `keystones` ADD `expired` TINYINT(1) NOT NULL DEFAULT \'0\''),
(369, 'ALTER TABLE `spawnableItems` ADD `craftable` TINYINT(1) NOT NULL DEFAULT \'1\' , ADD `devBlock` TINYINT(1) NOT NULL DEFAULT \'0\''),
(370, 'INSERT INTO `timedEvents` (`timer`, `delayMinutes`, `nextTime`, `disabled`) VALUES (\'announcements\', \'60\', CURRENT_TIMESTAMP, \'0\')'),
(371, 'ALTER TABLE `locations` ADD `hidden` TINYINT(1) NOT NULL DEFAULT \'0\''),
(372, 'ALTER TABLE `locations` CHANGE `currency` `currency` VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL'),
(373, 'ALTER TABLE `teleports` ADD `size` FLOAT(11) NOT NULL DEFAULT \'1.5\' COMMENT \'size of start tp\' , ADD `dsize` FLOAT(11) NOT NULL DEFAULT \'1.5\' COMMENT \'size of dest tp\''),
(374, 'ALTER TABLE `botChat` MODIFY `botChatID` int(11) NOT NULL AUTO_INCREMENT'),
(375, 'ALTER TABLE `botChatResponses` MODIFY `botChatResponseID` int(11) NOT NULL AUTO_INCREMENT'),
(376, 'INSERT INTO `timedEvents` (`timer`, `delayMinutes`, `nextTime`, `disabled`) VALUES (\'gimmeReset\', \'120\', CURRENT_TIMESTAMP, \'0\')'),
(377, 'ALTER TABLE `badItems` ADD `validated` TINYINT(1) NOT NULL DEFAULT \'1\''),
(378, 'ALTER TABLE `gimmePrizes` ADD `validated` TINYINT(1) NOT NULL DEFAULT \'1\''),
(379, 'ALTER TABLE `restrictedItems` ADD `validated` TINYINT(1) NOT NULL DEFAULT \'1\''),
(380, 'ALTER TABLE `shop` ADD `validated` TINYINT(1) NOT NULL DEFAULT \'1\''),
(381, 'UPDATE `teleports` SET size = 1.5 WHERE size = 0'),
(382, 'UPDATE `teleports` SET dsize = 1.5 WHERE dsize = 0'),
(383, 'ALTER TABLE `waypoints` CHANGE `steam` `steam` BIGINT(17) NOT NULL DEFAULT \'0\''),
(384, 'ALTER TABLE `events` CHANGE `steam` `steam` BIGINT(17) NOT NULL DEFAULT \'0\''),
(385, 'ALTER TABLE `lottery` CHANGE `steam` `steam` BIGINT(17) NOT NULL DEFAULT \'0\''),
(386, 'ALTER TABLE `memLottery` CHANGE `steam` `steam` BIGINT(17) NOT NULL DEFAULT \'0\''),
(387, 'ALTER TABLE `playerNotes` CHANGE `steam` `steam` BIGINT(17) NOT NULL DEFAULT \'0\''),
(388, 'ALTER TABLE `playerNotes` CHANGE `createdBy` `createdBy` BIGINT(17) NOT NULL DEFAULT \'0\''),
(389, 'ALTER TABLE `whitelist` CHANGE `steam` `steam` BIGINT(17) NOT NULL DEFAULT \'0\''),
(390, 'ALTER TABLE `memEntities` ENGINE = MEMORY'),
(391, 'ALTER TABLE `locations` ADD `locationCategory` VARCHAR(20) NOT NULL DEFAULT \'\''),
(392, 'ALTER TABLE `otherEntities` ADD `doNotDespawn` TINYINT NOT NULL DEFAULT \'0\''),
(393, 'ALTER TABLE `reservedSlots` CHANGE `steam` `steam` BIGINT(17) NOT NULL'),
(394, 'ALTER TABLE `reservedSlots` ENGINE = MEMORY'),
(395, 'ALTER TABLE `list` ADD `id` INT NOT NULL DEFAULT \'0\' , ADD `class` VARCHAR(20) NOT NULL DEFAULT \'\''),
(396, 'CREATE TABLE `gimmeGroup` (`groupName` varchar(30) NOT NULL DEFAULT \'\',PRIMARY KEY (`groupName`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4'),
(397, 'ALTER TABLE `shop` ADD `units` INT(1) NOT NULL, ADD `quality` INT(0) NOT NULL'),
(398, 'ALTER TABLE `server` ADD `baseProtectionExpiryDays` INT NOT NULL DEFAULT \'40\''),
(399, 'ALTER TABLE `waypoints` ADD `public` TINYINT(1) NOT NULL DEFAULT \'0\''),
(400, 'ALTER TABLE `players` ADD `VACBanned` TINYINT(1) NOT NULL DEFAULT \'0\''),
(401, 'ALTER TABLE `server` ADD `banVACBannedPlayers` TINYINT(1) NOT NULL DEFAULT \'0\''),
(402, 'LTER TABLE `server` CHANGE `lottery` `lottery` FLOAT(11) NOT NULL DEFAULT \'0\''),
(403, 'ALTER TABLE `server` CHANGE `lotteryMultiplier` `lotteryMultiplier` FLOAT(11) NOT NULL DEFAULT \'2\''),
(404, 'ALTER TABLE `server` CHANGE `zombieKillReward` `zombieKillReward` FLOAT(11) NOT NULL DEFAULT \'3\''),
(405, 'ALTER TABLE `server` ADD `deathCost` INT NOT NULL DEFAULT \'0\''),
(406, 'ALTER TABLE `players` DROP COLUMN showLocationMessages'),
(407, 'ALTER TABLE `server` ADD `showLocationMessages` TINYINT(1) NOT NULL DEFAULT \'1\''),
(408, 'ALTER TABLE `players` ADD `bountyReason` VARCHAR(100) NOT NULL DEFAULT \'\''),
(409, 'ALTER TABLE `server` ADD `bountyRewardItem` VARCHAR(25) NOT NULL DEFAULT \'cash\''),
(410, 'ALTER TABLE `server` ADD `enableLagCheck` TINYINT(1) NOT NULL DEFAULT \'1\''),
(411, 'ALTER TABLE `server` ADD `allowSecondBaseWithoutDonor` TINYINT(1) NOT NULL DEFAULT \'0\''),
(412, 'CREATE TABLE `connectQueue` (`id` bigint(20) NOT NULL AUTO_INCREMENT, `steam` bigint(17) NOT NULL, `command` varchar(255) NOT NULL, PRIMARY KEY (`id`)) ENGINE=MEMORY DEFAULT CHARSET=utf8mb4'),
(413, 'CREATE TABLE `connectQueue` (`id` bigint(20) NOT NULL AUTO_INCREMENT, `steam` bigint(17) NOT NULL, `command` varchar(255) NOT NULL, `processed` TINYINT(1) NOT NULL DEFAULT \'0\', PRIMARY KEY (`id`)) ENGINE=MEMORY DEFAULT CHARSET=utf8mb4'),
(414, 'CREATE TABLE `commandAccessRestrictions` (`id` int(11) NOT NULL, `functionName` varchar(100) NOT NULL DEFAULT \'\', `accessLevel` int(11) NOT NULL DEFAULT \'3\', PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4'),
(415, 'ALTER TABLE `server` ADD `nonAlphabeticChatReaction` VARCHAR(10) NOT NULL DEFAULT \'nothing\''),
(416, 'ALTER TABLE `teleports` ADD `minimumAccess` INT NOT NULL DEFAULT \'10000\', ADD `maximumAccess` INT NOT NULL DEFAULT \'0\''),
(417, 'ALTER TABLE `teleports` ADD `minimumAccess` INT NOT NULL DEFAULT \'0\', ADD `maximumAccess` INT NOT NULL DEFAULT \'0\''),
(418, 'ALTER TABLE `helpTopics` CHANGE `description` `description` TEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL DEFAULT \'\''),
(419, 'ALTER TABLE `helpTopics` CHANGE `topic` `topic` VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL'),
(420, 'ALTER TABLE `helpCommands` CHANGE `command` `command` TEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL DEFAULT \'\''),
(421, 'ALTER TABLE `helpCommands` CHANGE `description` `description` TEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL DEFAULT \'\''),
(422, 'ALTER TABLE `server` ADD `lotteryTicketPrice` INT NOT NULL DEFAULT \'25\'');

--
-- Dumping data for table `badItems`
--

INSERT INTO `badItems` (`item`, `action`, `validated`) VALUES
('artcube', 'timeout', 1),
('bedrock', 'timeout', 1),
('secureReinforcedDoorWooden', 'timeout', 1),
('vaultDoor03', 'timeout', 1);

--
-- Dumping data for table `gimmePrizes`
--

INSERT INTO `gimmePrizes` (`name`, `category`, `prizeLimit`, `quality`, `validated`) VALUES
('airFilter', 'misc', 1, 0, 1),
('aloeCream', 'health', 10, 0, 1),
('antibiotics', 'health', 4, 0, 1),
('baconAndEggs', 'food', 10, 0, 1),
('bakedPotato', 'food', 10, 0, 1),
('ballCap', 'clothes', 1, 0, 1),
('beer', 'food', 24, 0, 1),
('blackDenimPants', 'clothes', 1, 600, 1),
('bloodBag', 'health', 4, 0, 1),
('bloodDrawKit', 'health', 2, 0, 1),
('blueberryPie', 'food', 3, 0, 1),
('boneShiv', 'weapon', 1, 0, 1),
('brownDenimPants', 'clothes', 1, 600, 1),
('bucket', 'tool', 1, 0, 1),
('carBattery', 'misc', 1, 0, 1),
('clothGloves', 'clothes', 1, 600, 1),
('clothHat', 'clothes', 1, 600, 1),
('clothJacket', 'clothes', 1, 600, 1),
('clothPants', 'clothes', 1, 600, 1),
('coffee', 'food', 15, 0, 1),
('coffeeBeans', 'food', 20, 0, 1),
('cookingGrill', 'misc', 1, 0, 1),
('corn', 'food', 1, 0, 1),
('cornBread', 'food', 20, 0, 1),
('cornMeal', 'food', 20, 0, 1),
('cornOnTheCob', 'food', 20, 0, 1),
('cowboyHat', 'clothes', 1, 600, 1),
('denimPants', 'clothes', 1, 600, 1),
('dirt', 'misc', 50, 0, 1),
('doorKnob', 'misc', 5, 0, 1),
('driftwood', 'misc', 10, 0, 1),
('egg', 'food', 5, 0, 1),
('eggboiled', 'food', 5, 0, 1),
('femur', 'weapon', 20, 0, 1),
('firstAidKit', 'health', 3, 0, 1),
('foodHoney', 'food', 4, 0, 1),
('foodYuccaFruit', 'food', 10, 0, 1),
('foodYuccaJuice', 'food', 5, 0, 1),
('footballHelmet', 'clothes', 1, 0, 1),
('goldenRodTea', 'food', 15, 0, 1),
('grainAlcohol', 'food', 1, 0, 1),
('huntingKnife', 'weapon', 1, 600, 1),
('ice', 'misc', 1, 0, 1),
('ironChestArmor', 'clothes', 1, 600, 1),
('ironGloves', 'clothes', 1, 600, 1),
('ironHelmet', 'clothes', 1, 600, 1),
('ironLegArmor', 'clothes', 1, 600, 1),
('leatherGloves', 'clothes', 1, 600, 1),
('leatherJacket', 'clothes', 1, 600, 1),
('leatherPants', 'clothes', 1, 600, 1),
('meatStew', 'food', 3, 0, 1),
('miningHelmet', 'clothes', 1, 600, 1),
('moldyBread', 'food', 3, 0, 1),
('painkillers', 'food', 5, 0, 1),
('pistolBook', 'book', 1, 0, 1),
('plantFiberPants', 'clothes', 1, 0, 1),
('potato', 'food', 20, 0, 1),
('radiator', 'misc', 1, 0, 1),
('redDenimPants', 'clothes', 1, 0, 1),
('rottingFlesh', 'food', 10, 0, 1),
('scrapBrass', 'misc', 5, 0, 1),
('scrapChestArmor', 'clothes', 1, 600, 1),
('scrapGloves', 'clothes', 1, 600, 1),
('scrapHelmet', 'clothes', 1, 600, 1),
('scrapLegArmor', 'clothes', 1, 600, 1),
('shades', 'clothes', 1, 0, 1),
('shamSandwich', 'food', 20, 0, 1),
('skullCap', 'clothes', 1, 0, 1),
('skullCapBlack', 'clothes', 1, 0, 1),
('skullCapBlue', 'clothes', 1, 0, 1),
('skullCapBrown', 'clothes', 1, 0, 1),
('skullCapGreen', 'clothes', 1, 0, 1),
('skullCapRed', 'clothes', 1, 0, 1),
('tankTopBlue', 'clothes', 1, 0, 1),
('tankTopGreen', 'clothes', 1, 0, 1),
('tankTopPurple', 'clothes', 1, 0, 1),
('tankTopRed', 'clothes', 1, 0, 1),
('tankTopWhite', 'clothes', 1, 0, 1),
('theEnforcerMagazine', 'book', 1, 0, 1),
('tire', 'misc', 3, 0, 1),
('trophy', 'misc', 3, 0, 1),
('trophy2', 'misc', 3, 0, 1),
('trophy3', 'misc', 3, 0, 1),
('vegetableStew', 'food', 4, 0, 1),
('vitamins', 'food', 5, 0, 1),
('wrench', 'tool', 1, 0, 1);

--
-- Dumping data for table `gimmeZombies`
--

INSERT INTO `gimmeZombies` (`zombie`, `minPlayerLevel`, `minArenaLevel`, `entityID`, `bossZombie`, `doNotSpawn`, `maxHealth`, `remove`) VALUES
('zombieTemplateMale', 1, 1, 1, 0, 1, 0, 0),
('zombieWightFeral', 1, 1, 2, 0, 1, 0, 0),
('zombieWightFeralRadiated', 1, 1, 3, 0, 1, 0, 0),
('zombieBoe', 1, 1, 4, 0, 0, 0, 0),
('zombieBoeFeral', 1, 1, 5, 0, 1, 0, 0),
('zombieFootballPlayer', 1, 1, 6, 0, 0, 0, 0),
('zombieFemaleFat', 1, 1, 7, 0, 0, 0, 0),
('zombieFemaleFatFeral', 1, 1, 8, 0, 1, 0, 0),
('zombieJoe', 1, 1, 9, 0, 0, 0, 0),
('zombieJoeFeral', 1, 1, 10, 0, 1, 0, 0),
('zombieMoe', 1, 1, 11, 0, 0, 0, 0),
('zombieMoeFeral', 1, 1, 12, 0, 1, 0, 0),
('zombieArlene', 1, 1, 13, 0, 0, 0, 0),
('zombieArleneFeral', 1, 1, 14, 0, 1, 0, 0),
('zombieScreamer', 1, 1, 15, 0, 0, 0, 0),
('zombieScreamerFeral', 1, 1, 16, 0, 1, 0, 0),
('zombieDarlene', 1, 1, 17, 0, 0, 0, 0),
('zombieDarleneFeral', 1, 1, 18, 0, 1, 0, 0),
('zombieMarlene', 1, 1, 19, 0, 0, 0, 0),
('zombieMarleneFeral', 1, 1, 20, 0, 1, 0, 0),
('zombieYo', 1, 1, 21, 0, 0, 0, 0),
('zombieYoFeral', 1, 1, 22, 0, 1, 0, 0),
('zombieSteve', 1, 1, 23, 0, 0, 0, 0),
('zombieSteveFeral', 1, 1, 24, 0, 1, 0, 0),
('zombieSteveCrawler', 1, 1, 25, 0, 0, 0, 0),
('zombieSteveCrawlerFeral', 1, 1, 26, 0, 1, 0, 0),
('zombieBusinessMan', 1, 1, 27, 0, 0, 0, 0),
('zombieBusinessManFeral', 1, 1, 28, 0, 1, 0, 0),
('zombieSnow', 1, 1, 29, 0, 0, 0, 0),
('zombieSnowFeral', 1, 1, 30, 0, 1, 0, 0),
('zombieSpider', 1, 1, 31, 0, 0, 0, 0),
('zombieSpiderFeral', 1, 1, 32, 0, 1, 0, 0),
('zombieSpiderFeralRadiated', 1, 1, 33, 0, 1, 0, 0),
('zombieBurnt', 1, 1, 34, 0, 0, 0, 0),
('zombieNurse', 1, 1, 35, 0, 0, 0, 0),
('zombieNurseFeral', 1, 1, 36, 0, 1, 0, 0),
('zombieFatHawaiian', 1, 1, 37, 0, 0, 0, 0),
('zombieFatHawaiianFeral', 1, 1, 38, 0, 1, 0, 0),
('zombieFatCop', 1, 1, 39, 0, 1, 0, 0),
('zombieFatCopFeral', 1, 1, 40, 0, 1, 0, 0),
('zombieFatCopFeralRadiated', 1, 1, 41, 0, 1, 0, 0),
('zombieMaleHazmat', 1, 1, 42, 0, 0, 0, 0),
('zombieUtilityWorker', 1, 1, 43, 0, 0, 0, 0),
('zombieUtilityWorkerFeral', 1, 1, 44, 0, 1, 0, 0),
('zombieSoldier', 1, 1, 45, 0, 0, 0, 0),
('zombieSoldierFeral', 1, 1, 46, 0, 1, 0, 0),
('zombieSkateboarder', 1, 1, 47, 0, 0, 0, 0),
('zombieSkateboarderFeral', 1, 1, 48, 0, 1, 0, 0),
('zombieCheerleader', 1, 1, 49, 0, 0, 0, 0),
('zombieCheerleaderFeral', 1, 1, 50, 0, 1, 0, 0),
('zombieOldTimer', 1, 1, 51, 0, 0, 0, 0),
('zombieOldTimerFeral', 1, 1, 52, 0, 1, 0, 0),
('zombieBiker', 1, 1, 53, 0, 0, 0, 0),
('zombieFarmer', 1, 1, 54, 0, 0, 0, 0),
('zombieFarmerFeral', 1, 1, 55, 0, 1, 0, 0),
('zombieStripper', 1, 1, 56, 0, 0, 0, 0),
('zombieStripperFeral', 1, 1, 57, 0, 1, 0, 0),
('animalZombieDog', 1, 1, 63, 0, 1, 0, 0),
('animalZombieBear', 1, 1, 65, 0, 1, 0, 0),
('animalZombieVulture', 1, 1, 68, 0, 0, 0, 0);

--
-- Dumping data for table `otherEntities`
--

INSERT INTO `otherEntities` (`entity`, `entityID`, `doNotSpawn`, `doNotDespawn`) VALUES
('animalBear', 64, 0, 0),
('animalBoar', 70, 0, 0),
('animalChicken', 61, 0, 0),
('animalDireWolf', 67, 0, 0),
('animalRabbit', 60, 0, 0),
('animalSnake', 69, 0, 0),
('animalStag', 59, 0, 0),
('animalTemplateHostile', 62, 0, 0),
('animalTemplateTimid', 58, 0, 0),
('animalWolf', 66, 0, 0),
('Backpack', 74, 0, 0),
('DroppedLootContainer', 75, 0, 0),
('EvisceratedRemains', 76, 0, 0),
('invisibleAnimal', 77, 0, 0),
('invisibleAnimalEnemy', 78, 0, 0),
('minibike', 72, 0, 0),
('npcBanditBilly', 121, 0, 0),
('npcBanditDrake', 119, 0, 0),
('npcBanditDwarfSherry', 123, 0, 0),
('npcBanditKane', 125, 0, 0),
('npcBanditLeader', 83, 0, 0),
('npcBanditLeaderPete', 120, 0, 0),
('npcBanditMelee', 81, 0, 0),
('npcBanditMichael', 118, 0, 0),
('npcBanditMichelle', 127, 0, 0),
('npcBanditRanged', 82, 0, 0),
('npcBanditRoger', 124, 0, 0),
('npcBanditSasha', 122, 0, 0),
('npcBanditShahala', 126, 0, 0),
('npcFemaleMeleeBanditTemplate', 116, 0, 0),
('npcFemaleRangedBanditTemplate', 117, 0, 0),
('npcMaleMeleeBanditTemplate', 114, 0, 0),
('npcMaleRangedBanditTemplate', 115, 0, 0),
('npcSurvivorBill', 109, 0, 0),
('npcSurvivorBob', 106, 0, 0),
('npcSurvivorEmma', 111, 0, 0),
('npcSurvivorFemaleRangedTemplate', 105, 0, 0),
('npcSurvivorFemaleTemplate', 104, 0, 0),
('npcSurvivorHannah', 112, 0, 0),
('npcSurvivorKevin', 107, 0, 0),
('npcSurvivorLarry', 108, 0, 0),
('npcSurvivorMaleRangedTemplate', 103, 0, 0),
('npcSurvivorMaleTemplate', 102, 0, 0),
('npcSurvivorRanged', 80, 0, 0),
('npcSurvivorSheela', 110, 0, 0),
('npcSurvivorTemplate', 79, 0, 0),
('npcSurvivorZoey', 113, 0, 0),
('npcTraderBob', 87, 0, 0),
('npcTraderHugh', 89, 0, 0),
('npcTraderJimmy', 88, 0, 0),
('npcTraderJoel', 85, 0, 0),
('npcTraderRekt', 86, 0, 0),
('npcTraderTemplate', 84, 0, 0),
('npcTravelingTraderBob', 137, 0, 0),
('npcTravelingTraderHugh', 139, 0, 0),
('npcTravelingTraderJimmy', 138, 0, 0),
('npcTravelingTraderJoel', 135, 0, 0),
('npcTravelingTraderRekt', 136, 0, 0),
('npcTravelingTraderTemplate', 134, 0, 0),
('sc_General', 73, 0, 0),
('supplyPlane', 71, 0, 0);

--
-- Dumping data for table `proxies`
--

INSERT INTO `proxies` (`scanString`, `action`, `hits`) VALUES
('ALIBABA.COM', 'ban', 0),
('AMAZON TECHNOLOGIES', 'ban', 0),
('AOYOUHOST', 'ban', 0),
('AZURE TECHNOLOGY', 'ban', 0),
('BANK OF AMERICA', 'ban', 0),
('CHOOPA', 'ban', 0),
('DCSMANAGE.COM', 'ban', 0),
('EDIS.AT', 'ban', 0),
('EGIHOSTING', 'ban', 0),
('ETHR-NET', 'ban', 0),
('FEDERAL ONLINE GROUP', 'ban', 0),
('GAMESERVER', 'ban', 0),
('GLOBAL-FRAG-SERVERS', 'ban', 0),
('GORILLASERVERS', 'ban', 0),
('HUGESERVER', 'ban', 0),
('KRYPT TECHNOLOGIES', 'ban', 0),
('LONGLING', 'ban', 0),
('LONLIFE.CN', 'ban', 0),
('MULTACOM', 'ban', 0),
('PCCWGLOBAL.COM', 'ban', 0),
('PSYCHZ-NETWORKS', 'ban', 0),
('QUADRANET', 'ban', 0),
('SAKURA', 'ban', 0),
('TATA COMMUNICATIONS', 'ban', 0),
('VELIA.NET', 'ban', 0),
('WEB2OBJECTS', 'ban', 0),
('WEBNX.COM', 'ban', 0),
('WIRELESS-ALARM.COM', 'ban', 0),
('YPSOLUTIONS', 'ban', 0),
('ZENLAYER', 'ban', 0);

--
-- Dumping data for table `restrictedItems`
--

INSERT INTO `restrictedItems` (`item`, `qty`, `accessLevel`, `action`, `validated`) VALUES
('44MagBullet', 480, 90, 'timeout', 1),
('762mmBullet', 480, 90, 'timeout', 1),
('9mmBullet', 480, 90, 'timeout', 1),
('dynamite', 5, 90, 'exile', 1),
('rocket', 99, 90, 'exile', 1);

--
-- Dumping data for table `shop`
--

INSERT INTO `shop` (`item`, `category`, `price`, `stock`, `idx`, `maxStock`, `variation`, `special`, `validated`, `units`, `quality`) VALUES
('ammo9mmBullet', 'ammo', 3, 500, 3, 500, 0, 0, 1, 0, 0),
('armorMiningHelmet', 'clothing', 125, 15, 2, 15, 0, 0, 1, 0, 0),
('carBattery', 'machines', 120, 100, 1, 100, 0, 0, 1, 0, 0),
('drinkJarBeer', 'food', 10, 20, 2, 20, 0, 0, 1, 0, 0),
('drinkJarCoffee', 'food', 30, 10, 3, 10, 0, 0, 1, 0, 0),
('drinkJarGoldenRodTea', 'food', 35, 10, 6, 10, 0, 0, 1, 0, 0),
('drugAntibiotics', 'medic', 100, 10, 1, 10, 0, 0, 1, 0, 0),
('drugPainkillers', 'medic', 25, 13, 5, 13, 0, 0, 1, 0, 0),
('drugVitamins', 'medic', 40, 10, 7, 10, 0, 0, 1, 0, 0),
('firstAidKitSchematic', 'books', 125, 5, 1, 5, 0, 0, 1, 0, 0),
('foodBaconAndEggs', 'food', 30, 10, 1, 10, 0, 0, 1, 0, 0),
('foodCornBread', 'food', 1, 100, 4, 100, 0, 0, 1, 0, 0),
('foodHoney', 'food', 25, 100, 5, 100, 0, 0, 1, 0, 0),
('foodMeatStew', 'food', 50, 18, 7, 18, 0, 0, 1, 0, 0),
('leatherDuster', 'clothing', 50, 50, 1, 50, 0, 0, 1, 0, 0),
('medicalFirstAidBandage', 'medic', 50, 10, 3, 10, 0, 0, 1, 0, 0),
('medicalFirstAidKit', 'medic', 100, 50, 4, 50, 0, 0, 1, 0, 0),
('medicalSplint', 'medic', 18, 500, 6, 500, 0, 0, 1, 0, 0),
('resourceConcreteMix', 'housing', 8, 2000, 1, 2000, 0, 0, 1, 0, 0),
('resourceCropCoffeeBeans', 'garden', 50, 10, 1, 10, 0, 0, 1, 0, 0),
('resourceFeather', 'misc', 2, 5000, 1, 5000, 0, 0, 1, 0, 0),
('resourceFemur', 'misc', 2, 500, 2, 500, 0, 0, 1, 0, 0),
('resourceGlue', 'misc', 5, 500, 3, 500, 0, 0, 1, 0, 0),
('resourceHeadlight', 'misc', 60, 50, 4, 50, 0, 0, 1, 0, 0),
('resourceOil', 'misc', 15, 5000, 5, 5000, 0, 0, 1, 0, 0),
('resourceRepairKit', 'ammo', 25, 10, 4, 10, 0, 0, 1, 0, 0),
('smallEngine', 'machines', 180, 100, 6, 100, 0, 0, 1, 0, 0),
('storeShelving01', 'housing', 8, 500, 4, 500, 0, 0, 1, 0, 0),
('storeShelving01Double', 'housing', 8, 500, 5, 500, 0, 0, 1, 0, 0),
('storeShelving01Top', 'housing', 8, 500, 6, 500, 0, 0, 1, 0, 0),
('storeShelving01TopDouble', 'housing', 8, 500, 7, 500, 0, 0, 1, 0, 0),
('toolAndDieSet', 'misc', 120, 35, 6, 35, 0, 0, 1, 0, 0),
('toolBeaker', 'medic', 300, 5, 2, 5, 0, 0, 1, 0, 0);

--
-- Dumping data for table `shopCategories`
--

INSERT INTO `shopCategories` (`category`, `idx`, `code`) VALUES
('ammo', 6, 'a'),
('books', 10, 'b'),
('clothing', 1, 'cl'),
('food', 10, 'f'),
('garden', 5, 'g'),
('housing', 1, 'h'),
('machines', 1, 'ma'),
('medic', 8, 'm'),
('misc', 1, 'mis');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
